server:
  port: 9191


spring:
  application:
    name: banking-service
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: aa
    password: aa

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
